spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.sqlpub.com:3306/cinema
    username: cinema1895
    password: 4DAH3AsbUFFcihud

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的转化